### ISSUE TITLE
Field's value for checkboxes and radios is not being read properly

### ISSUE THREAD

**Issue by hnordt** [jaredpalmer/formik#1024]
### Current Behavior

Field's value for checkboxes and radios is not being read properly.

### Expected behavior

Values for checkboxes and radios should be read from Formik state and not from props.

### Reproducible example

https://codesandbox.io/s/ppy7wyrl0m

### Suggested solution(s)

I think the problem lies here: https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L155-L158

I believe the fix would be changing:

```js
      value:
        props.type === 'radio' || props.type === 'checkbox'
          ? props.value // React uses checked={} for these inputs
          : getIn(formik.values, name),
``` 

To:

```js
     [props.type === 'radio' || props.type === 'checkbox' ? "checked" : "value"]:
       getIn(formik.values, name),
``` 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.3.1
| React            | 16.5.2

**Comment by dem0nbruce** [comment]
I also have this issue where checkboxes aren't binding correctly.

**Comment by gzzo** [comment]
What's also interesting is that it doesn't seem to be respecting the `value` passed to `props` either:

https://codesandbox.io/s/n5ozork8vm

I would expect `isEnabled` to be the value of the input when it's checked, `test`, in this case.

**Comment by zzuber** [comment]
@jaredpalmer I agree. Not having the ability to get the value from a checkbox or radio limits formik awesomeness!!!

**Comment by smithcoin** [comment]
I was trying to look through the docs and I can't figure out how to get the value from a radio input. Is this issue closed?

I would love to see this feature implemented.

**Comment by giorgioongithub** [comment]
+1

**Comment by jankalfus** [comment]
@smithcoin I believe this is the minimum working example for radio buttons: https://codesandbox.io/s/88jqoy4qvl

**Comment by tonyhallett** [comment]
This is still an issue

**Comment by smithcoin** [comment]
Why was this issue closed? The bug still exists.

**Comment by jaredpalmer** [comment]
This has been fixed in v2.

**Comment by zzuber** [comment]
@jaredpalmer when is v2 going to be released?

**Comment by gregoralbrecht** [comment]
@jaredpalmer We're using `v2.0.1-rc.5` and it seems like we still have this issue. Basically the same setup as in @hnordt's [codesandbox](https://codesandbox.io/s/r1r6x1wp94), except we're using `useField()` instead of `<Field>`. Not sure if we're doing anything wrong, but other types of inputs work just fine.

**Comment by sgnl** [comment]
When is v2 going to be release?

Better yet, anyway we can help to fix this?

**Comment by shamseerahammedm** [comment]
> @smithcoin I believe this is the minimum working example for radio buttons: https://codesandbox.io/s/88jqoy4qvl

This is the only solution that worked for me after 4 hours of banging my head

**Comment by joeyorlando** [comment]
This is still a problem...

**Comment by abouzeyd** [comment]
hello everybody i'have issue i work with Formik so i want that if i'm select one checkbox it deselect other  someone can help me
