### ISSUE TITLE
[v2] isValid=true on mount, even though initialValues are invalid and validateOnMount=true

### ISSUE THREAD

**Issue by Martaver** [jaredpalmer/formik#1950]
### Current Behavior

isValid is true once the form mounts, even though the validationSchema invalidates initialValues and the form is untouched.

### Expected behavior

isValid prop to reflect the actual validity of the form at all times. Due to initialErrors, validating on mount automatically may be undesirable, which is understandable. So in this case, explicitly setting validateOnMount=true should definitely ensure isValid prop's value on mount is correct. 

### Reproducible example
Using Formik 2.0.3, an invalid form's isValid prop is true on mount. validateOnMount props doesn't seem to make a difference.

https://codesandbox.io/s/formik-example-zehlg

### Suggested solution(s)

 - default isValid to false, as a start, if no initialErrors are provided. Hard to imagine a form that's valid with initialValues, unless you're reloading old values.
 - ensure that validateOnMount=true runs validation against initialValues during mount, so that isValid's initial value is correct.

### Additional context

N/A

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.3
| React            | 16.11.0
| TypeScript       | 3.6.4
| Browser          | Chrome 77.0.3865.120
| npm/Yarn         | yarn 1.19.0
| Operating System | macos 10.14.6 (18G103)

**Comment by nperrier** [comment]
I'm running into this issue too. I have `validateOnMount` set but I don't see any of my Field validation functions running and `isValid` is `true`.

**Comment by nperrier** [comment]
I don't see where in the source code that `validationOnMount` is referenced:

https://github.com/jaredpalmer/formik/search?q=validateOnMount&unscoped_q=validateOnMount

It looks like it was never implemented? If that's the case, remove it from the docs.

**Comment by hannupekka** [comment]
I too had problems with `validateOnMount` and noticed this: https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L350

As a workaround, I have this hook in my form to do the validation on mount:
```
useEffect(() => {
  (async () => validateForm())();
}, []);
```

**Comment by jonathanwelton** [comment]
Does anyone know why `validateOnMount` was commented out and when it will be fully implemented?

**Comment by clintonb** [comment]
This is fixed in release 2.0.4.

**Comment by igorkrup** [comment]
I don't think is fixed. I forked @Martaver sandbox and changed to version `2.0.4`

https://codesandbox.io/s/formik-example-jwwu5

I console.log `isValid` and initial is always `true`, then after first rerender it becomes `false`

**Comment by mustafawm** [comment]
@igorkrup yeah... I ended up using hannupekka's useEffect workaround.

**Comment by djensen47** [comment]
I usually don't like to bump an issue but this is still happening despite being "stale."

**Comment by djensen47** [comment]
@hannupekka @mustafawm How did you get the `validateForm` outside of the context of the `<Formik>` component? Or are you using `useFormik`?

**Comment by tar-aldev** [comment]
Any update on this? It seems like I can use dirty as a workaround, but still the issue exists.
Initially ```isValid === true``` and ```isValidating === false```. Sometimes on new page it is not visible, but when navigating between tabs it can be seen

**Comment by crhayes** [comment]
When specifying `validateOnMount={true}`, `isValidating` is `false` on first render. It seems like `isValidating` should be `true` in this case.

**Comment by hmac2222** [comment]
+1

**Comment by johnrom** [comment]
I wouldn't be against setting isValidating to true on initial render when validateOnMount is true. It's technically a lie, so we'd have to make sure that if validation never runs (is that possible?) it would revert back to false at some point.

**Comment by gael33** [comment]
+1
I suggest `isValid` should be `false` until at least one validation has been executed.

**Comment by TomBerriot** [comment]
+1

**Comment by crhayes** [comment]
> I suggest isValid should be false until at least one validation has been executed.

An issue I have with this approach is that it's perfectly reasonable to pre-fill a form with valid data and specify `validateOnMount={false}`. In that case I would expect `isValid` to be true.

**Comment by parzivalClaus** [comment]
> When specifying `validateOnMount={true}`, `isValidating` is `false` on first render. It seems like `isValidating` should be `true` in this case.

Specifying validadeOnMount={true} works for what I need, thanks.

**Comment by NeliHarbuzava** [comment]
`validadeOnMount: true` not working with `useFormik`. Any updates on this?

**Comment by charleshimmer** [comment]
Same issue here. A hacky workout around for me right now is `isInitialValid={false}` which isn't always true. Would be better if validateOnMount={true} worked.

**Comment by TNAJanssen** [comment]
I also have the same issue, does anybody have a clue where the problems lies?

**Comment by martaver** [comment]
I think the difficulty with providing a comprehensive solution to this problem is that 'validation' can include custom validators that are async and can make requests to check validity. If we are re-evaluating validation state immediately on init, then potentially it would run all of those requests again which is undesirable.

I think the only viable solution to a problem like this is to capture 'validation state' and load it simultaneously with initial values, and this is non-trivial.

I'm not certain, but that's probably the reason there hasn't been a 'quick fix' for this. @jaredpalmer is this the case?

**Comment by jaredpalmer** [comment]
Well summarized. This is the problem.
GitHub <notifications@github.com> wrote:
“I think the difficulty with providing a comprehensive solution to this problem is that 'validation' can include custom validators that are async and can make requests to check validity. If we are re-evaluating validation state immediately on init, then potentially it would run all of those requests again which is undesirable.

I think the only viable solution to a problem like this is to capture 'validation state' and load it simultaneously with initial values, and this is non-trivial.

I'm not certain, but that's probably the reason there hasn't been a 'quick fix' for this. @jaredpalmer is this the case?”

**Comment by martaver** [comment]
So... its non-trivial... but can we do it anyway? :D

**Comment by C-E-Rios** [comment]
This is working for me on version `2.1.5` both with `useFormik` and `<Formik />`

**Comment by mrlaseptima** [comment]
i have same issue . but i solve this with some codes : 
i set isInitialValid to a state that have a same name (isInitialValid).
and change this state just with  schema.validate every time my defaultValues changed.

`
const [isInitialValid, setIsInitialValid] = useState(false);'

 useEffect(() => {
    schema
      .validate(defaultValues)
      .then((res) => setIsInitialValid(true))
      .catch((err) => setIsInitialValid(false));
  }, [defaultValues]);

  return ( 
<Formik
        initialValues={defaultValues}
        enableReinitialize
        isInitialValid={isInitialValid} 
        validationSchema={schema}
       >

        //my fileds

</Formik>

`

**Comment by C-E-Rios** [comment]
**Formik@2.1.4**

https://codesandbox.io/s/formik-example-forked-dgf5j?file=/index.js

**Comment by akhatriST** [comment]
Looks like the fix is not available in Formik@2.1.5. 

Tried out 2.1.4 and it is working fine as expected with `validateOnMount={true}`

**Comment by mariusLionte123** [comment]
I am usint 2.1.5 and validateOnMount={true} is not working.

**Comment by JaredDahlke** [comment]
as a new Formik user I just had to downgrade from 2.1.5 to 2.1.4 for validateOnMount={true} to actually work/fill the error object. Why was it removed in 2.1.5?

amazing tool by the way thank you for all of your work making this.

**Comment by dommangetnicolas** [comment]
I've done it by doing that:

```
const formRef = useRef<any>();

useEffect(() => {
    formRef?.current?.validateForm();
}, []);

<Formik
    innerRef={formRef}
    validationSchema={validation}
    initialValues={{password: ''}}
    validateOnMount
    onSubmit={(values, formikHelpers) => onSubmit(values, formikHelpers)}>
</Formik>
```

**Comment by bitworking** [comment]
I have a problem that seems to be related: I first have to submit the form and only after that the validation on change takes place. The validation on blur works without submitting first.

**Comment by matin-binary** [comment]
When specifying `isValid`, you can get `dirty` as well and add it to your condition `is_disabled={!dirty || isSubmitting || !isValid}`

**Comment by farzanfx** [comment]
best approach to set initial validation to false I found a prop called : `isInitialValid`.
here is my code and my initial validation to set submit button disabled or not I used it in such a way?
`    const formik = useFormik({
        initialValues: {
            firstName: firstName,
            lastName: lastName
        },
        validationSchema: Yup.object({
            firstName: Yup.string()
                .max(15, 'Must be 15 characters or less')
                .required('Required'),
            lastName: Yup.string()
                .max(20, 'Must be 20 characters or less')
                .required('Required'),
        }),
        isInitialValid : false
    });`

and my button : 
`<Button
    fullWidth
    color="primary"
    margin="normal"
    variant="contained"
    disabled={!formik.isValid}
    onClick={() => nextHandler()}
>`

**Comment by superamxpruebas** [comment]
> best approach to set initial validation to false I found a prop called : `isInitialValid`.
> here is my code and my initial validation to set submit button disabled or not I used it in such a way?
> ` const formik = useFormik({ initialValues: { firstName: firstName, lastName: lastName }, validationSchema: Yup.object({ firstName: Yup.string() .max(15, 'Must be 15 characters or less') .required('Required'), lastName: Yup.string() .max(20, 'Must be 20 characters or less') .required('Required'), }), isInitialValid : false });`
> 
> and my button :
> `<Button disabled={!formik.isValid} onClick={() => nextHandler()} >`

yes, this pretty much solves it (formik 2.2.5)

**Comment by joaopaulobdac** [comment]
For now that works for me too, but there's this warning:
`Warning: isInitialValid has been deprecated and will be removed in future versions of Formik. Please use initialErrors or validateOnMount instead.`

**Comment by johnrom** [comment]
isInitialValid is now !empty(initialErrors), so you should be able to do `initialErrors={{ manuallyIndicatingAn: "Error" }}`, or just run your `validate()` function on `initialValues`, which we don't do within a Formik render because we cannot prove it to be render safe / it may be expensive or async for some users

**Comment by flormasuyama** [comment]
This is the workaround I found since `isValid` is `true` when the form loads:
`isEmpty` belongs to lodash lib.

`disabled={!dirty || !isValid || !isEmpty(errors)}`

**Comment by laurensdacosta** [comment]
This is how I solved it:
`const InitialValidate = () => {
   const { values, submitForm, validateForm, dirty } = useFormikContext();
   React.useEffect(() => dirty && (() => validateForm())(), [values, submitForm]);
   return null;
};`

Component:
`<InitialValidate />`

**Comment by schester44** [comment]
yikes

**Comment by shinchannn** [comment]
Seems it's been resolved in Formik 2.2.9

**Comment by NutchaponMake** [comment]
for me it still not resolved  in 2.2.9
I using this work around
 disabled={
              !formik.dirty ||
              !formik.isValid ||
              !Object.keys(formik.errors).length === 0
            }

**Comment by SSOURABH58** [comment]
formik has a prop called `isInitialValid`, setting it to `false` solves the issue easily
```isInitialValid={false}```

I think it's the intended way to do it, and with that, we can mark the issue closed 🟣

example :
```
<Formik
        validationSchema={ValidationSchema}
        initialValues={{ email: '', password: '' }}
        onSubmit={values => onSubmit(values.email, values.password)}
        isInitialValid={false}  // <----- add this and you are good to go : )
      >
``` 

any responses are appreciated 😉

**Comment by AnandBhandari1** [comment]
In the ValidationSchema I did like this
```
 validateOnMount: true,
    enableReinitialize: true,
```
This worked for `"formik": "^2.2.9",`

**Comment by SnakeHead** [comment]
> ```
>  validateOnMount: true,
>     enableReinitialize: true,
> ```

Definitely DOES NOT work for me!  Can't believe this hasn't been fixed yet, using version 2.2.9.

**Comment by kristof-mattei** [comment]
Using `useFormik()` and doing `validateOnMount` causes my form to load with an enabled button and then within a split second disable.

**Comment by rwb196884** [comment]
Is there a way to get validation to run initially? I can't get any of this to work -- seems to be completely fucked.

**Comment by mizrab** [comment]
Facing same issue on `"formik?: "^2.4.2"`

**Comment by mbeltramin93** [comment]
> Facing same issue on `"formik?: "^2.4.2"`

I don't, it seems to work with 2.4.3 version.

**Comment by kristof-mattei** [comment]
Managed to create a reproducible example:

https://codesandbox.io/s/formik-valid-when-it-shouldnt-be-h3hzxf

Best way to see it is deployed: https://h3hzxf.csb.app/ Refresh the page and you can see the submit button being enabled before it being disabled.

I've also added a 'log' of states that occur. In my opinion it should never be valid, as we load the form with invalid data.

![Animation2](https://github.com/jaredpalmer/formik/assets/864376/ab5c9804-276c-4570-802c-9fd391bc89b6)

**Comment by gabrielareia** [comment]
Facing the same issue. We should have an immediate feedback when `validateOnMount` is true.

**Comment by jjcoll** [comment]
I got my desired behaviour like this: 

```typescript

      useEffect(() => {
          const validate = async () => {
            try {
              await storySchema.validate(data, { abortEarly: false });
              setInitialValidity(true);
            } catch (error) {
              setInitialValidity(false);
            }
          };
          validate();
        }, [data]);

return (
    <Formik
      initialValues={data}
      onSubmit={onSubmit}
      validationSchema={storySchema}
      validateOnMount={true}
    >
      {({
        values,
        errors,
        touched,
        handleChange,
        handleBlur,
        isValid,
        setFieldValue,
        dirty,
      }) => {


        const formIsValid = dirty
          ? isValid // If user made changes, use current form validity
          : initialValidity; // Otherwise, check if coming from a later step with valid data

return (
          <Form>
/*rest of the form*/

<Button type="submit" disabled={!formIsValid}>
                {isLoading ? "Creating Profile..." : "Complete Setup"}
              </Button>
```

I was looking for this behaviour: 
- Initial Button State: Buttons should be disabled when a form first loads to prevent users from proceeding with invalid data
- Coming Back from Later Steps: When returning from a later form step, buttons should be enabled if the data is valid
- Error Display: Validation errors should only show after user interaction, not on initial form load
- Dynamic Validation: If a user makes changes that invalidate the form, the button should become disabled again
