### ISSUE TITLE
Field props are not typed

### ISSUE THREAD

**Issue by iwarshak** [jaredpalmer/formik#2086]
### Current Behavior

FieldProps are not typed appropriately when using `<Field>`

<img width="572" alt="Screen Shot 2019-12-05 at 9 29 54 AM" src="https://user-images.githubusercontent.com/471/70253221-68b50780-1748-11ea-9f68-adc28b67bf9e.png">

However, manually typing it seems to fix the warning

<img width="666" alt="Screen Shot 2019-12-05 at 10 47 28 AM" src="https://user-images.githubusercontent.com/471/70255597-b29fec80-174c-11ea-86ab-2e24aada8c5d.png">

I implemented the Field based on the [TS guide](https://jaredpalmer.com/formik/docs/guides/typescript)

### Expected behavior

I expected TS to not give a warning here since I followed the example of the guides.

### Reproducible example

Here is a sample: https://codesandbox.io/s/hopeful-sunset-5n7ud

### Suggested solution(s)

My knowledge of TS may not be deep enough to say whether it TS should error on this, or if it really is the case that I need to coerce the props to `FieldProps` in the last codesandbox sample.

If that's the case then the guide should be updated, and I am happy to do it and submit a PR.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.6
| React            | 16.2.0
| TypeScript       | 3.7.2
| Browser          | Chrome
| npm/Yarn         |
| Operating System | Mac

**Comment by RichardLindhout** [comment]
I ended up doing this:

```
import { Formik, Field, Form, FieldProps } from 'formik'
import TextField from '@material-ui/core/TextField'
```
```
interface FormValues {
  title: string
}
```
```
<Formik
      initialValues={initialValues}
      validationSchema={schema}
      onSubmit={onSubmit}
      render={formikBag => (
        <Form>
          <Field
            name="title"
            render={({
              field,
              form: { isSubmitting },
              meta,
            }: FieldProps<FormValues>) => (
              <TextField
                {...field}
                disabled={isSubmitting}
                type="text"
                variant="outlined"
                error={meta.touched && !!meta.error}
                helperText={meta.touched && meta.error}
                label={'Titel'}
                fullWidth
              />
            )}
          />
        </Form>
      )}
    />
```

**Comment by RichardLindhout** [comment]
Looks like it's a bug in TypeScript or something

**Comment by lightwave** [comment]
If I interpret the type info in Field.d.ts correctly, render gets passed a props argument of type FieldConfig<any> instead of FieldProps<FormValues> in your case.  If you look at Field.d.ts, there are quite a lot of places where 'any' type is used.

**Comment by RichardLindhout** [comment]
It would be better if the unkown type was used https://mariusschulz.com/blog/the-unknown-type-in-typescript

**Comment by lightwave** [comment]
The following definition of FieldProps is incorrect in my humble opinion. FieldInputProps and FieldMetaProps takes a type parameter of V to denote the type of a field value. However, FormikProps expects a type parameter to denote the type of the values of a form.  So, in FieldProps, FormikProps shouldn't take V as the type parameter.

This hasn't caused a problem in most project, I think, primarily due to the fact that most project are using the Field component which set V to any.

However, if you start using useField in Typescript, it causes type error.

```typescript
export interface FieldProps<V = any> {
  field: FieldInputProps<V>;
  form: FormikProps<V>; // if ppl want to restrict this for a given form, let them.
  meta: FieldMetaProps<V>;
}
```

**Comment by jaredpalmer** [comment]
Fixed in 2.1.

**Comment by andrewpeterprifer** [comment]
@jaredpalmer could you please provide a minimal code snippet using `<Field>` with `children` that TypeScript shouldn't be complaining about? I'm on Formik 2.1.1 and TypeScript 3.7.4 and I'm still getting the "Binding element 'field'/'meta'/'etc' implicitly has an 'any' type." errors for the example typescript code on the Formik website.

**Comment by davidwilson3** [comment]
@andrewpeterprifer  @jaredpalmer 

This is still an issue for me too.  I'm on Formik 2.1.3 and Typescript 3.7.5 and am receiving these implicit any errors.

Error example: "Binding element 'setSubmitting' implicitly has an 'any' type."  Has anyone found a consistent solution to this?

**Comment by unframework** [comment]
Also experiencing the same issue with Formik 2.1.4 and Typescript 3.7.4.

**Comment by AndrewPrifer** [comment]
@davidwilson3 I think explicitly typing the field props will always be necessary because otherwise TypeScript would have absolutely no way of telling which field a certain Field component belongs to. My complaint was more directed to the documentation. @jaredpalmer maybe the Field component could be made more ergonomic by letting it accept a generic type parameter like useField does?

**Comment by delewis13** [comment]
Same issue Formik 2.1.4, typescript 3.8.3

**Comment by NicolasMarino** [comment]
Any updates on this?

Same issue in Formik 2.1.5, typescript 3.8.3

**Comment by RichardLindhout** [comment]
Maybe you need to 

<Formik<FormValues>
abc={etc}

**Comment by jarodburchill** [comment]
This is still not fixed in v2.2.6

**Comment by bkiac** [comment]
Issue still persists in v2.2.9 with `typescript@4.3.4`

**Comment by johnrom** [comment]
It's not advisable to create a new functional component in each render to pass to the component prop, as React will not be able to tell they are the same component. If you want to use render props, it is recommended to use a child function which should be typed correctly.

Types overhaul is targeted for 3.1 and a preview is possible by searching PRs for "Strongly Typed Formik v3", though your particular case is not tested as `component` should not be created on-the-fly.

**Comment by bkiac** [comment]
I did use render props with a child function but `props` is `any`, I used @RichardLindhout solution (https://github.com/formium/formik/issues/2086#issuecomment-566071198) to specify the types
```ts
<Field name="period">
	{(props: FieldProps<string>) => ( // `props` is `any` without `FieldProps`
		<select {...props.field}>
			<option value="current">Current</option>
			<option value="next">Next</option>
			<option value="both">Both</option>
		</select>
	)}
</Field>
```

**Comment by skele2k** [comment]
One way around this problem is creating custom component and using 
`
type InputFieldProps = InputHTMLAttributes<HTMLInputElement> & {
    label: string;
    name: string;
    textarea?: boolean;
  };

export const InputField: React.FC<InputFieldProps> = ({
    const [field, {error}] = useField(props);

`

**Comment by lehnavid** [comment]
Problem still occurs.
Typescript: 4.5.2
Formik: 2.2.9

**Comment by daniellin215** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/41842771/153547553-730aa479-abcc-4eed-9495-2a826871aa92.png">
@jaredpalmer given a snippet below, what types should we use? You said this is fixed but it doesn't seem so: 
`<Field name="lastName">
                {({ field, form }) => (
                  <FormControl
                    isInvalid={form.errors.lastName && form.touched.lastName}
                  >
                    <FormLabel color={"lightGray"} htmlFor="lastName">
                      Last name
                    </FormLabel>
                    <Input
                      {...field}
                      size="md"
                      id="lastName"
                      placeholder="Anderson"
                    />
                    <FormErrorMessage>{form.errors.lastName}</FormErrorMessage>
                  </FormControl>
                )}
              </Field>`

**Comment by kimgysen** [comment]
Still a problem
<img width="278" alt="Screenshot 2022-05-26 at 14 48 00" src="https://user-images.githubusercontent.com/4547364/170490649-20061f9c-a0ed-4779-93a9-69685f763a41.png">

**Comment by martinbliss** [comment]
FYI Formik's documentation is misleading and should be corrected to avoid confusion by TS consumers. While Formik was written in TypeScript, this issue makes it clear that Formik does not yet support strong typing, and therefor intermediate/advanced use cases (e.g. `<Field ...>{({field}) => ... } </Field>`) are not yet supported for TypeScript consumers who care about strong typing. I also checked the API reference for `<Field />` and it doesn't mention anything about this gap either. Surprisingly, [other libraries](https://chakra-ui.com/docs/components/form/form-control#usage-with-form-libraries) which _**are**_ strongly typed recommend Formik without mentioning this gap either.

Pages I checked just now:
https://formik.org/docs/guides/typescript
https://formik.org/docs/examples/typescript
https://formik.org/docs/api/field

**Comment by Joshuajrodrigues** [comment]
https://chakra-ui.com/docs/components/form-control/usage#usage-with-form-libraries

Form Libraries like [Formik](https://jaredpalmer.com/formik/) make it **soooo** easy to manage form state and validation.

well that was a lie
   <Field name="name">
                {({ field, form }) => (//Binding element 'field' implicitly has an 'any' type.
                  <FormControl isRequired
                    isInvalid={form.errors.name && form.touched.name}
                  >
                    <FormLabel aria-required >Name</FormLabel>
                    <Input  {...field} name="name" type={"text"} />
                    <FormErrorMessage>{form.errors.name}</FormErrorMessage>
                  </FormControl>
                )}
              </Field>

**Comment by ODelibalta** [comment]
This is still an issue for me. I'd appreciate any help. 

```
"use client";

import {
  Box,
  Button,
  Checkbox,
  Container,
  FormControl,
  FormLabel,
  Heading,
  HStack,
  Input,
  Stack,
  PasswordField,
  FormErrorMessage,
} from "@myapp/ui";
import { useBreakpointValue, useColorModeValue } from "@chakra-ui/react";
import { Formik, Field, Form, FormikHelpers } from "formik";
import { object, string } from "yup";

interface Values {
  password: string;
  email: string;
}

let formSchema = object().shape({
  email: string().email().required("Email is required"),
  password: string().required("Password is required"),
});

const Login: React.FC = () => {
  const handleSubmit = (values: Values) => {
    console.log(values);
  };

  return (
    <Container
      maxW="lg"
      py={{ base: "12", md: "24" }}
      px={{ base: "0", sm: "8" }}
    >
      <Stack spacing="8">
        <Stack spacing="6">
          <Stack spacing={{ base: "2", md: "3" }} textAlign="center">
            <Heading size={useBreakpointValue({ base: "xs", md: "sm" })}>
              Log in to your account
            </Heading>
          </Stack>
        </Stack>
        <Box
          py={{ base: "0", sm: "8" }}
          px={{ base: "4", sm: "10" }}
          bg={useBreakpointValue({ base: "transparent", sm: "bg-surface" })}
          boxShadow={{ base: "none", sm: useColorModeValue("md", "md-dark") }}
          borderRadius={{ base: "none", sm: "xl" }}
        >
          <Formik
            initialValues={{
              password: "",
              email: "",
            }}
            validationSchema={formSchema}
            onSubmit={(values: Values) => handleSubmit(values)}
          >
            {({ errors }) => (
              <Form>
                <Stack spacing="6">
                  <Stack spacing="5">
                    <Field name="email" id="email" type="email">
                      {({ field, form }) => (
                        <FormControl
                          isInvalid={form.errors.email && form.touched.email}
                        >
                          <FormLabel htmlFor="email">Email</FormLabel>
                          <Input {...field} required />
                          <FormErrorMessage>
                            {form.errors.email}
                          </FormErrorMessage>
                        </FormControl>
                      )}
                    </Field>
                    <Field name="password" id="password" type="password">
                      {({ field, form }) => (
                        <FormControl
                          isInvalid={
                            form.errors.password && form.touched.password
                          }
                        >
                          <FormLabel htmlFor="password">Password</FormLabel>
                          <PasswordField {...field} />
                          <FormErrorMessage>
                            {form.errors.password}
                          </FormErrorMessage>
                        </FormControl>
                      )}
                    </Field>
                  </Stack>
                  <HStack justify="space-between">
                    <Checkbox defaultChecked>Remember me</Checkbox>
                    <Button variant="link" colorScheme="blue" size="sm">
                      Forgot password?
                    </Button>
                  </HStack>
                  <Stack spacing="6">
                    <Button
                      variant="primary"
                      disabled={errors.email || errors.password ? true : false}
                      type="submit"
                    >
                      Sign in
                    </Button>
                  </Stack>
                </Stack>
              </Form>
            )}
          </Formik>
        </Box>
      </Stack>
    </Container>
  );
};

export default Login;

```

**Comment by johnrom** [comment]
This library hasn't had activity in quite a while. You can look at my implementation here which came close to solving the problem:

https://github.com/jaredpalmer/formik/pull/3152

But I think React Hook Form has since solved a lot of the advanced types required for forms in their library since then.

**Comment by ODelibalta** [comment]
@johnrom I really appreciate the mention of the other library. Thank you so much I am going try that one.
