### ISSUE TITLE
Strange link when on TypeScript page in documentation which breaks navigation

### ISSUE THREAD

**Issue by vexleet** [jaredpalmer/formik#3658]
### Current Behavior

When you are using the documentation and go to the guide about TypeScript some kind of a link shows up which makes the navigation not usable (not scrollable and clickable).

![image](https://user-images.githubusercontent.com/18427030/191959787-44631f5a-1d86-45cf-b9e1-3e3c449409c1.png)

### Expected behavior

To have a link to TypeScript Types and a working navigation when on this page of the documentation.

### Reproducible example

Go to [https://formik.org/docs/guides/typescript ](https://formik.org/docs/guides/typescript) and try to use the navigation

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Version 105.0.5195.127 (Official Build) (64-bit)

**Comment by MostafaKMilly** [comment]
I discover the issue was solved https://github.com/jaredpalmer/formik/commit/e677bea8181f40e6762fc7e7fb009122384500c6

**Comment by vexleet** [comment]
> I discover the issue was solved [e677bea](https://github.com/jaredpalmer/formik/commit/e677bea8181f40e6762fc7e7fb009122384500c6)

Navigation still doesn't work correctly when on TypeScript page. It's not scrollable and when you click on something it goes to npm.
