### ISSUE TITLE
[TS] Beta : Props of FastField are missing

### ISSUE THREAD

**Issue by pierre-H** [jaredpalmer/formik#634]
**Describe the bug**
Since the beta version, the props of the FastField component are missing : there is a `any`.

**To Reproduce**
Just install formik

**Expected behavior**
Props of FastField are defined

---

- Formik Version: beta 1
- React Version: 16.3.2
- TypeScript Version: 2.8.3
- CodeSandbox Link:
- OS: Windows 10 64bits
- Node Version: 10.1.0
- Package Manager and Version: 5.6.0

**Comment by pierre-H** [comment]
Any news ?

**Comment by jaredpalmer** [comment]
This should all be fixed with moving to 2.9.x

**Comment by pierre-H** [comment]
Thanks : I will try it and update this issue asap

**Comment by pierre-H** [comment]
Still have the same problem with TS 2.9.1

For example, the definition of FastField is : 

```tsx
/// <reference types="react" />
import * as React from 'react';
export interface FastFieldState {
    value: any;
    error?: string;
}
export declare const FastField: React.ComponentClass<any> & {
    WrappedComponent: React.ComponentClass<any>;
};
```

The problem is that the prop def is fastfield is any with that ...

**Comment by pierre-H** [comment]
@jaredpalmer  any idea ?

**Comment by pierre-H** [comment]
Tried with TS 3.0.1 and Formik 1.0.2 …
That's very annoying … Someone has an idea ?
@jaredpalmer ?

**Comment by pierre-H** [comment]
It's like #768
